version: '3'
services:
  redmine:
    image: redmine:3.3
    ports:
      - 8000:3000
    environment:
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_PASSWORD: example
    volumes:
      - filevolume:/usr/src/redmine/files
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mysql:5.6
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    volumes:
      - datavolume:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: always
  gitbucket:
    build: ./gitbucket

volumes:
  datavolume:
  filevolume:
    
