version: '3'

services:

  redmine:
    image: redmine:3.3
    ports:
      - 8000:3000
    environment:
      REDMINE_DB_MYSQL: mysql_redmine
      REDMINE_DB_PASSWORD: redmine
    volumes:
      - redmine_filevolume:/usr/src/redmine/files
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mysql_redmine
    restart: always

  mysql_redmine:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: redmine
      MYSQL_DATABASE: redmine
    volumes:
      - redmine_dbvolume:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: always

  gitbucket:
    build: ./gitbucket
    ports:
      - 8080:8080
    environment:
      GITBUCKET_DB_URL: jdbc:mysql://mysql_gitbucket/gitbucket?useUnicode=true&characterEncoding=utf8
      GITBUCKET_DB_USER: gitbucket
      GITBUCKET_DB_PASSWORD: gitbucket
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

  mysql_gitbucket:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: gitbucket
      MYSQL_DATABASE: gitbucket
    volumes:
      - gitbucket_dbvolume:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: always

volumes:
  redmine_dbvolume: {}
  redmine_filevolume: {}
  gitbucket_dbvolume: {}

