version: '3'

services:

  redmine:
    image: redmine:3.3
    ports:
      - 50001:3000
    environment:
      REDMINE_DB_MYSQL: mysql_redmine
      REDMINE_DB_PASSWORD: redmine
      HTTP_PROXY: ${http_proxy}
      HTTPS_PROXY: ${https_proxy}
    volumes:
      - redmine_filevolume:/usr/src/redmine/files
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mysql_redmine
    restart: always

  mysql_redmine:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: redmine
      MYSQL_DATABASE: redmine
    volumes:
      - redmine_dbvolume:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: always

  gitbucket:
    build: ./gitbucket
    ports:
      - 50002:8080
    environment:
      GITBUCKET_DB_URL: jdbc:mysql://mysql_gitbucket/gitbucket?useUnicode=true&characterEncoding=utf8
      GITBUCKET_DB_USER: gitbucket
      GITBUCKET_DB_PASSWORD: gitbucket
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mysql_gitbucket
    restart: always

  mysql_gitbucket:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: gitbucket
      MYSQL_DATABASE: gitbucket
    volumes:
      - gitbucket_dbvolume:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: always

  rocketchat:
    image: rocket.chat
    ports:
      - 50003:3000
    environment:
      MONGO_URL: mongodb://mongodb_rocketchat:27017/mydb
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mongodb_rocketchat
    restart: always

  mongodb_rocketchat:
    image: mongo:3.4
    volumes:
      - rocketchat_dbvolume:/data/db
      - /etc/localtime:/etc/localtime:ro
    restart: always

volumes:
  redmine_dbvolume: {}
  redmine_filevolume: {}
  gitbucket_dbvolume: {}
  rocketchat_dbvolume: {}
